version: "3.8"

services:
  backend:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./volumes:/app/volumes
    environment:
      - DATABASE_URL=sqlite:///./volumes/elections.db

volumes:
  db_data:
    driver: local
